### ISSUE TITLE
RocketMod4

### ISSUE THREAD

**Issue by BraianKant** [RestoreMonarchyPlugins/WipeScheduler#1]
Hello! I don't know how to contact you, then I go here. Can u make something like WipeScheduler for RocketMod4?

**Comment by RestoreMonarchy** [comment]
Hey You can join my Discord and we can talk there https://discord.gg/yBztk3w

**Comment by RestoreMonarchy** [comment]
OR add me through the Steam https://steamcommunity.com/id/RestoreMonarchy/

**Comment by BraianKant** [comment]
Thanks =)
